"use client";

import { useEffect } from "react";

const STYLE_ID = "kpoparkive-ve3-panel-base-style";

export default function VisualEditorV3PanelBaseStyle() {
  useEffect(() => {
    const style = document.createElement("style");
    style.id = STYLE_ID;
    style.textContent = `
/* Shared inspector shell */
.kpoparkiveVe3FootnotePanel,.kpoparkiveVe3MediaPanel,.kpoparkiveVe3StructurePanel{position:fixed;right:14px;top:112px;max-height:calc(100vh - 128px);overflow:auto;border:1px solid #d8d0eb;border-radius:12px;background:rgba(255,255,255,.99);box-shadow:0 18px 55px rgba(39,28,70,.22);color:#342c40}
.kpoparkiveVe3FootnotePanel{z-index:12120;width:min(450px,calc(100vw - 28px))}.kpoparkiveVe3MediaPanel{z-index:12130;width:min(470px,calc(100vw - 28px))}.kpoparkiveVe3StructurePanel{z-index:12140;width:min(520px,calc(100vw - 28px))}

/* Footnotes */
.kpoparkiveVe3FootnoteMarker{cursor:pointer!important;outline:1px dotted rgba(107,60,232,.5);outline-offset:2px;border-radius:3px}.kpoparkiveVe3FootnoteMarker:hover{background:rgba(107,60,232,.09)}.kpoparkiveVe3FootnoteMarker[data-wiki-footnote=""]{opacity:.35;text-decoration:line-through}
.kpoparkiveVe3FootnoteHeader,.kpoparkiveVe3FootnotePicker,.kpoparkiveVe3FootnoteEditor{padding:12px 14px}.kpoparkiveVe3FootnoteHeader{display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid #e6e0ef;background:#fbf9ff}.kpoparkiveVe3FootnoteHeader>div{display:grid;gap:2px}.kpoparkiveVe3FootnoteHeader strong{color:#5832c6}.kpoparkiveVe3FootnoteHeader span{font-size:11px;color:#82768e}.kpoparkiveVe3FootnoteHeader button,.kpoparkiveVe3FootnotePicker button,.kpoparkiveVe3FootnoteEditor button,.kpoparkiveVe3FootnotePicker select,.kpoparkiveVe3FootnoteEditor textarea{border:1px solid #dcd5e8;border-radius:8px;background:#fff;color:#352e40;font:inherit}.kpoparkiveVe3FootnoteHeader button{width:32px;height:32px;font-size:20px;cursor:pointer}.kpoparkiveVe3FootnotePicker{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.kpoparkiveVe3FootnotePicker select{min-width:0;height:36px;padding:0 8px}.kpoparkiveVe3FootnotePicker button{padding:0 10px;cursor:pointer}.kpoparkiveVe3FootnoteEditor{display:grid;gap:9px;border-top:1px solid #eee9f4}.kpoparkiveVe3FootnoteEditor label{font-size:12px;font-weight:800}.kpoparkiveVe3FootnoteEditor textarea{min-height:118px;padding:9px;resize:vertical;line-height:1.45}.kpoparkiveVe3FootnoteEditor small{color:#82768e;line-height:1.45}.kpoparkiveVe3FootnoteEditor .locked{color:#9a6b36}.kpoparkiveVe3FootnoteActions{display:flex;justify-content:flex-end;gap:8px}.kpoparkiveVe3FootnoteEditor button{height:36px;padding:0 12px;cursor:pointer;font-weight:800}.kpoparkiveVe3FootnoteEditor button.danger{color:#a22a3c}.kpoparkiveVe3FootnoteEditor button:disabled{opacity:.45;cursor:default}

/* Media */
.kpoparkiveVe3MediaTarget{outline:2px solid rgba(107,60,232,.42)!important;outline-offset:3px;cursor:pointer!important}.kpoparkiveVe3MediaTarget:hover{outline-color:rgba(107,60,232,.9)!important}.kpoparkiveVe3MediaHeader,.kpoparkiveVe3MediaPicker,.kpoparkiveVe3MediaBody{padding:12px 14px}.kpoparkiveVe3MediaHeader{display:flex;align-items:center;justify-content:space-between;gap:10px;border-bottom:1px solid #e6e0ef;background:#fbf9ff}.kpoparkiveVe3MediaHeader>div{display:grid;gap:2px}.kpoparkiveVe3MediaHeader strong{color:#5832c6}.kpoparkiveVe3MediaHeader span{font-size:11px;color:#82768e}.kpoparkiveVe3MediaHeader button,.kpoparkiveVe3MediaPicker button,.kpoparkiveVe3MediaPicker select,.kpoparkiveVe3MediaBody input,.kpoparkiveVe3MediaBody button{border:1px solid #dcd5e8;border-radius:8px;background:#fff;color:#352e40;font:inherit}.kpoparkiveVe3MediaHeader button{width:32px;height:32px;font-size:20px;cursor:pointer}.kpoparkiveVe3MediaPicker{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.kpoparkiveVe3MediaPicker select{height:36px;min-width:0;padding:0 8px}.kpoparkiveVe3MediaPicker button{padding:0 10px;cursor:pointer}.kpoparkiveVe3MediaBody{display:grid;gap:12px;border-top:1px solid #eee9f4}.kpoparkiveVe3MediaBody label{display:grid;gap:5px;font-size:12px;font-weight:800}.kpoparkiveVe3MediaBody input{height:36px;padding:0 9px;min-width:0}.kpoparkiveVe3MediaParam{display:grid;grid-template-columns:110px minmax(0,1fr) auto;gap:7px;align-items:center}.kpoparkiveVe3MediaParam code{font-size:11px;overflow:hidden;text-overflow:ellipsis}.kpoparkiveVe3MediaParam button{height:34px;padding:0 9px;cursor:pointer}.kpoparkiveVe3MediaParam.locked{opacity:.62}.kpoparkiveVe3MediaAdd{display:grid;grid-template-columns:110px minmax(0,1fr) auto;gap:7px}.kpoparkiveVe3MediaMeta{font-size:11px;color:#82768e;line-height:1.45}.kpoparkiveVe3MediaDirty{color:#6b3ce8;font-weight:800}.kpoparkiveVe3MediaRemove{color:#a22a3c}.kpoparkiveVe3MediaFooter{display:flex;justify-content:flex-end;gap:8px}.kpoparkiveVe3MediaFooter button{height:36px;padding:0 12px;cursor:pointer;font-weight:800}

/* Structure */
.kpoparkiveVe3StructureHeader,.kpoparkiveVe3StructureTabs,.kpoparkiveVe3StructureBody{padding:12px 14px}.kpoparkiveVe3StructureHeader{display:flex;align-items:center;justify-content:space-between;gap:10px;border-bottom:1px solid #e6e0ef;background:#fbf9ff}.kpoparkiveVe3StructureHeader>div{display:grid;gap:2px}.kpoparkiveVe3StructureHeader strong{color:#5832c6}.kpoparkiveVe3StructureHeader span{font-size:11px;color:#82768e}.kpoparkiveVe3StructureHeader button,.kpoparkiveVe3StructureTabs button,.kpoparkiveVe3StructureBody button,.kpoparkiveVe3StructureBody select,.kpoparkiveVe3StructureBody input,.kpoparkiveVe3StructureBody textarea{border:1px solid #dcd5e8;border-radius:8px;background:#fff;color:#352e40;font:inherit}.kpoparkiveVe3StructureHeader button{width:32px;height:32px;font-size:20px;cursor:pointer}.kpoparkiveVe3StructureTabs{display:flex;gap:7px;border-bottom:1px solid #eee9f4}.kpoparkiveVe3StructureTabs button{height:34px;padding:0 11px;cursor:pointer;font-weight:800}.kpoparkiveVe3StructureTabs button.active{border-color:#6b3ce8;color:#5832c6;background:#f4f0ff}.kpoparkiveVe3StructureBody{display:grid;gap:11px}.kpoparkiveVe3StructureBody label{display:grid;gap:5px;font-size:12px;font-weight:800}.kpoparkiveVe3StructureBody input,.kpoparkiveVe3StructureBody select{height:36px;padding:0 9px;min-width:0}.kpoparkiveVe3StructureBody textarea{min-height:112px;padding:9px;resize:vertical;line-height:1.45}.kpoparkiveVe3StructureGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.kpoparkiveVe3StructureActions{display:flex;justify-content:flex-end;gap:8px}.kpoparkiveVe3StructureActions button{height:36px;padding:0 12px;cursor:pointer;font-weight:800}.kpoparkiveVe3StructureActions .primary{border-color:#6b3ce8;background:#6b3ce8;color:#fff}.kpoparkiveVe3StructureList{display:grid;gap:6px}.kpoparkiveVe3StructureRow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;padding:8px;border:1px solid #ece7f2;border-radius:8px}.kpoparkiveVe3StructureRow div{min-width:0;display:grid;gap:2px}.kpoparkiveVe3StructureRow b{font-size:11px}.kpoparkiveVe3StructureRow span{font-size:11px;color:#82768e;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kpoparkiveVe3StructureRow button{height:32px;padding:0 9px;cursor:pointer}.kpoparkiveVe3StructureRow button.danger{color:#a22a3c}.kpoparkiveVe3PendingDelete{outline:2px solid rgba(180,45,65,.7)!important;opacity:.42!important}.kpoparkiveVe3StructureNote{font-size:11px;color:#82768e;line-height:1.5}.kpoparkiveVe3StructureDirty{color:#6b3ce8;font-weight:800}

@media(max-width:760px){.kpoparkiveVe3FootnotePanel,.kpoparkiveVe3MediaPanel,.kpoparkiveVe3StructurePanel{top:150px;max-height:calc(100vh - 164px)}.kpoparkiveVe3MediaParam,.kpoparkiveVe3MediaAdd{grid-template-columns:90px minmax(0,1fr) auto}.kpoparkiveVe3StructureGrid{grid-template-columns:1fr}}
`;
    document.head.appendChild(style);
    return () => style.remove();
  }, []);
  return null;
}
